name: desafio_blink
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/res/

  fonts:
    - family: Montserrat
      fonts:
        - asset: fonts/Montserrat-Black.ttf
          weight: 900
        - asset: fonts/Montserrat-Bold.ttf
          weight: 700
        - asset: fonts/Montserrat-Regular.ttf
          weight: 400
        - asset: fonts/Montserrat-ExtraLight.ttf
          weight: 200
    - family: Rouge
      fonts:
        - asset: fonts/RougeScript-Regular.ttf
          weight: 400